---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_user: root
      connection: local
lint:
  name: yamllint
platforms:
  - name: localhost
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: travis
verifier:
  name: testinfra
  lint:
    name: flake8
